project:
  type: website
  output-dir: docs
  resources:
  - "googlecd08604f4edafe6e.html"

  preview:
    browser: false
    port: 6074

website:
  title: "Dati aperti sul PNRR"
  site-url: https://pnrr.datibenecomune.it/
  repo-url: https://github.com/ondata/italian-public-sector-pnrr-data-guide
  repo-actions: [edit, issue]
  page-navigation: true
  favicon: images/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - href: introduzione.qmd
        text: Introduzione
      - href: monitoraggio/index.qmd
        text: Monitoraggio
      - section: Fonti
        contents:
          - section: OpenCUP
            href: fonti/opencup/index.qmd
            contents:
              - href: fonti/opencup/focus-pnrr.qmd
                text: Focus PNRR
          - section: ANAC
            href: fonti/anac/index.qmd
            contents:
              - href: fonti/anac/informazioni-cig.qmd
                text: Estrarre i dati ANAC
          - section: Servizio Contratti Pubblici
            href: fonti/scp/index.qmd
            contents:
              - href: fonti/scp/informazioni-scp.qmd
                text: Estrarre i dati SCP
          - href: fonti/openbdap/index.qmd
            text: OpenBDAP
      - href: guide/procedura-esempio.qmd
        text: Esempio estrazione dati
      - text: "---"
      - section: Rete monitoraggio PNRR
        href: rete-pnrr.md
        contents:
          - href: datibenecomune.md
            text: datiBeneComune
          - href: osservatorio.md
            text: Osservatorio PNRR
          - href: openpnrr.md
            text: Open PNRR
          - href: https://www.monithon.eu/it/
            text: Monithon
            target: "_blank"
          - href: https://www.thinktankperiod.org/
            text: think tank Period
            target: "_blank"
      - href: quinto-piano-governo-aperto.md
        text: OGP e altre iniziative istituzionali
      - text: "---"
      - href: https://vorrei.datibenecomune.it/
        text: I dati che vorrei

  twitter-card:
    creator: "@ondatait"
    card-style: summary_large_image
    image: "/images/cover-og.png"
    description: "Per chi vuole raccogliere informazioni sul Piano, correlarle tra loro e arricchirle, e per monitorarlo ed estrapolare nuovi punti di sintesi."
  open-graph:
    locale: it_IT
    image: "/images/cover-og.png"
    description: "Per chi vuole raccogliere informazioni sul Piano, correlarle tra loro e arricchirle, e per monitorarlo ed estrapolare nuovi punti di sintesi."


  page-footer:
    right: "Un sito costruito con ❤️ e con [Quarto](https://quarto.org/)."
    left: "[CC-BY](https://creativecommons.org/licenses/by/4.0/) [#datiBeneComune](https://datibenecomune.it/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-filter: '^.*pnrr\.datibenecomune\.it\/'
    lang: "it-IT"

execute:
  daemon: false
  freeze: auto
