project:
  type: website
  output-dir: docs

  preview:
    browser: false
    port: 6074

website:
  title: "Dati aperti sul PNRR"
  site-url: https://ondata.github.io/italian-public-sector-pnrr-data-guide
  repo-url: https://github.com/ondata/italian-public-sector-pnrr-data-guide
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: introduzione.qmd
        text: Introduzione
      - section: Fonti
        contents:
          - href: fonti/opencup/index.qmd
            text: OpenCUP
            contents:
              - href: fonti/opencup/focus-pnrr.qmd
                text: Focus PNRR
          - href: fonti/anac/index.qmd
            text: ANAC
            contents:
              - href: fonti/anac/informazioni-cig.qmd
                text: Estrarre i dati ANAC
          - href: fonti/scp/index.qmd
            text: Servizio Contratti Pubblici
            contents:
              - href: fonti/scp/informazioni-scp.qmd
                text: Estrarre i dati SCP
          - href: fonti/openbdap/index.qmd
            text: OpenBDAP
      - href: guide/procedura-esempio.qmd
        text: Esempio estrazione dati
      - text: "---"
      - href: datibenecomune.md
        text: datiBeneComune
      - href: osservatorio.md
        text: Osservatorio PNRR
      - href: openpnrr.md
        text: Open PNRR
      - href: quinto-piano-governo-aperto.md
        text: V Piano Nazionale Governo Aperto

  page-footer:
    right: "Un sito costruito con ❤️ e con [Quarto](https://quarto.org/)."
    left: "[CC-BY](https://creativecommons.org/licenses/by/4.0/) [#datiBeneComune](https://datibenecomune.it/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    link-external-filter: '^.*ondata\.github\.io\/italian-public-sector-pnrr-data-guide'
    lang: "it-IT"
    bibliography: open-pnrr.bib

execute:
  daemon: false
  freeze: auto
