title: "<title>"
labels: [proposte]
body:
- type: markdown
  attributes:
    value: |
      Se hai proposte e idee per arricchire e migliorare [**questa guida**](https://pnrr.datibenecomune.it/), scrivicelo qui sotto.<br>Ricordati che si rivolge a quelle persone che vogliono raccogliere informazioni sul Piano, per correlarle tra loro e arricchirle, per monitorarlo ed estrapolare nuovi punti di sintesi
- type: textarea
  attributes:
    label: Testo
    description: "Scrivi la tua proposta:"
  validations:
    required: true
