title: "<title>"
labels: [raccontaci]
body:
- type: markdown
  attributes:
    value: |
      Se [**questa guida**](https://pnrr.datibenecomune.it/) ti è stata utile per **comprendere meglio** qualcosa sul PNRR, se l'hai usata per impostare un'**azione di monitoraggio**, se l'hai usata per **costruire qualcosa di nuovo**, raccontacelo qui.
- type: textarea
  attributes:
    label: Testo
    description: "Scrivi qui il tuo racconto:"
  validations:
    required: true
