labels: [aiuto]
body:
- type: markdown
  attributes:
    value: |
      ## Richiesta di aiuto
      Qui rispondiamo a richieste di aiuto legate a quanto descritto [in questa guida guida](https://pnrr.datibenecomune.it/), non a domande generiche sui dati del PNRR.
- type: textarea
  attributes:
    label: Testo
    description: Scrivi il testo della tua richista
  validations:
    required: true
