name: aggiorna pagina web dati Italiadomani

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '53 2 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile scrape, installa pandoc
      run: |-
        mkdir -p ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x scrape
        sudo pip install yq
        sudo apt-get install pandoc
    - name: aggiorna pagina
      run: |-
        export PATH=$PATH:~/bin
        cd ./script/italia-domani/
        chmod +x ./italia-domani-pagina-catalogo.sh
        ./italia-domani-pagina-catalogo.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "pagina dati italiadomani: ${timestamp}" || exit 0
        git push
